version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - 3333:3306
      - 3366:3306
    hostname: db
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    build: .
    ports:
      - "9000:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
