version: '2'
services:
  app:
    image: php:7.0-apache
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    ports:
      - 3333:3306
      - 3366:3306
    hostname: db
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
