# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "blog"
  config.vm.hostname = "blog"
  config.vm.network :private_network, ip: "192.168.33.70"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/3657281/centos64_ja.box"
  config.vm.synced_folder "../", "/var/www/html", create: true, owner: "vagrant", group: "vagrant"
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  config.vm.provider :virtualbox do |vb|
    vb.name = "blog"
    vb.gui = false
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "shell", privileged: false do |shell|
    shell.path = "setup.sh"
    shell.args = 'vagrant'
  end
end
